##七牛云的key
qiniu:
  accessKey: canKgBzqR_AN_EviuOuWYUT4Vko3gi5dTNZFiQ4C
  secretKey: feAWGHn_UmhGU2ckkHd9F2q2qFpC7lPqlemvEOCH
  bucketName: eumji025
  basePath: http://of8rkrh1w.bkt.clouddn.com/

#数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: HTML5
  #字符集和json格式工具
  http:
    encoding:
      charset: utf-8
    converters:
      preferred-json-mapper: jackson
    multipart:
      max-file-size: 10MB
  application:
    name: eumji-blog

#mynatis配置
mybatis:
  type-aliases-package: com.eumji.zblog.vo
  #mapper加载路径
  mapper-locations: classpath:mapper/*Mapper.xml
  #myatbis配置文件
  config-location: classpath:mybatis-conf.xml

server:
  session-timeout : 3600
  port: 8080





